### ISSUE TITLE
Adding/Deleting/Editing/Loading Images

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#114]
There are issues with images and this may be the system bogging down with such large data. Here is what I know so far using Collection: Claire's Test and Specimen: Claire's specimen test.

- I am able to delete most images whether there are on a shared drive, a link, or on my private drive.
- The flower image is just a problem no matter where it resides, also in Mush Valley, Quarry 31. Trying to delete it from edit or delete will crash my system such that I have to close the window and open a new window. Doesn't matter if I start from a fresh login. I'm not sure what is special about that image.
- Sometimes receive this error when trying to add an image, ex. .jpg of small size: Error: Cannot read properties of undefined (reading '_fields')
- Need to retest scrolling ability once these issues resolved. The system was being "finicky/inconsistent" at this time

**Comment by aazaff** [comment]
This sounds serious. We will need to investigate this before the hackathon, but I will not commit to having it DONE before hackathon.

**Comment by NoisyFlowers** [comment]
First bullet: Is this a description of a problem?

Second bullet: I was able to delete the flower image in Claire's test collection/Claire's test specimen 1. However, I could only do this after editing it to add a Category. The lack of Category was likely due to it being created before this field was made required. This misconfiguration should not reccur one we clean out the db.

Third bullet: This was an artifact of [https://github.com/paleobot/pbot-client/issues/24](https://github.com/paleobot/pbot-client/issues/24).

Fourth bullet: This was address in paleobot/pbot-client@674f8775ffc510531b0e0a44a0ebe4f243b2b49c.

**Comment by clairecleveland** [comment]
First bullet: This tells you that sometimes deleting images works.
Second bullet: This tells you sometimes it doesn't and gave an example. 
Third bullet: Cool, so does not give error anymore and is not a problem anymore?
Fourth bullet: @NoisyFlowers So based on above, should this issue be closed?

**Comment by NoisyFlowers** [comment]
I can't promise there aren't still issues. Image upload is a complicated little stack. But the one's listed here appear to be addressed.
