### ISSUE TITLE
Description entry lagging behind user keystrokes

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#212]
This was reported during HackAThon; however, this was likely due to wifi lag rather than PBot lag. This will need to be retested prior to next PBot launch.  

Description of issue: This is an observation- entering info in description is lagging pretty hardcore with all the users on. Its two states behind populating (hard to see if it really got what I clicked). (CR) UPDATE: lag continues but if you’re adding two states (one with order 1 and another with order 2, and you haven't waited the requisite 15 seconds to satisfy the lag, you will enter the second state with the order defaulting to one (assuming the second entry doesn't see the one in the order from the first state)

**Comment by aazaff** [comment]
Not sure how to classify this one. Calling it a bug for now.

**Comment by ecurrano** [comment]
I have done a lot of entry these past week and am not able to recreate this. Of course, probably no one else is also entering data. I have noticed that the dropdown menus and the specimen page can be slow to load in dev, perhaps because we now have so many specimens in there (yay, Matt's bulk uploader!).
