### ISSUE TITLE
Private-Public issues

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#235]
I tried to edit a private description (MLA Characters - LNL) for a specimen in a private collection (Hubble Bubble...), and got the error message:

Error: Unable to cascade groups for Description

The specimen has been assigned as to the private OTU "LNL (Lepto-Nano Legume)"

**Comment by NoisyFlowers** [comment]
The isDuplicate routine in Resolvers.js is called for every node type but has no logic for CharacterInstance, since those are actually handled in raw cypher. This resulted in an exception, which prevented group cascade. 

The solution is to return a valid stub value from isDuplicate when the nodeType is CharacterInstance.

This is in paleobot/pbot-api@37f598197dd6eb5406af3566f55ea0a279bfe283

**Comment by NoisyFlowers** [comment]
Merged to master and deployed to dev and stage
