### ISSUE TITLE
How will we handle comment tracking?

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#24]
## Options
1. As a `:Comment` node ~~(boooo)~~ (I favour this now)
2. As a `[:COMMENT_ON]` relation from a user to another node, with the actual comment as a property of the relation (I like this because it lets you comment on a lot of stuff.)
~~3. Use some system totally external to the graph database? (I see pros and cons to this... guess it would depend on what was used and I don't really have an idea of the options out there)~~
~~4. Do we even still need/want comments?~~
5. Create an intermediate node (analogous to characterinstance) that we can attach a comment to.
  
We should deal with this after the workshop in conjunction with resolving #20

**Comment by aazaff** [comment]
Another option

5. Instead of allowing free-text "comments" having some kind of pre-set list of labels - e.g.., "like', "thumbs-up", "dubious" - similar to GitHub labels

**Comment by NoisyFlowers** [comment]
I think 1, 2, and 5 are the most worth discussing. 

I don't have the same "booo" feeling about 1, because expanding relationships to include a transition node is warranted in some instances (we might consider this for quantitative HAS_STATE relationships at some point, for instance). But I agree that we'd likely start with 2 before going to 1. 

I particularly like the scoring approach of 5, though, as it allows us to do some quantitative analysis based on the comment.

**Comment by aazaff** [comment]
I also liked 5, however, based on my sense from the workshop it seems that they will want to be able to convey much more complex commentary than could be encapsulated in just a few pre-set labels. Perhaps some hybrid approach where there is a free-text comment, but the user has to tag it with some overarching label (again, similar to how github issues are done).

**Comment by aazaff** [comment]
One of the things we discussed was adding an intermediate node for EXAMPLE_OF relationships. This is because a user might want to question (comment) on whether a specimen really is a particular example of an OTU. In that case we would need a node to attach the comment to as relations cannot point to other relations.

**Comment by aazaff** [comment]
This is redundant with the work happening in #58
