### ISSUE TITLE
Create Supporting Administrative Information

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#27]
Not really an issue, but trying to use GitHub to organize ideas...

One of the EarthCube committees put together a really great [Community Participation Guidelines](https://www.earthcube.org/community-participation-guidelines).

**Comment by aazaff** [comment]
I renamed this issue to reflect the broader sets of documentation we have to create.

- [ ] Community Participation Guidelines
- [ ] Software Licenses
- [ ] Data Licenses
- [ ] Executive committee by-laws

Any others?

**Comment by clairecleveland** [comment]
This is definitely a good document to use as a guide.

**Comment by aazaff** [comment]
https://www.geosociety.org/gsa/membership/code-of-ethics/gsa/membership/code-of-ethics.aspx

**Comment by clairecleveland** [comment]
@ecurrano This is in progress now. We should probably come up with a list of tasks and prioritize after HackAThon.

**Comment by aazaff** [comment]
Activities related to this were explicitly proposed in the failed FY24 geoinformatics proposal. Because the FY25 proposal will be a partnership with PBDB, which has its own governance structure, we would have to be significantly revise this anyway. Closing for now and we can open a new issue if/when 2.0 happens.
