### ISSUE TITLE
Recover entry if there is an error

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#274]
I entered a new OTU, but had quotes in the name, which is not currently allowed. When I submitted the OTU, I got taken to a new screen with my error message, and lost everything I had painstakingly typed in. Is there a way to change this so that the user doesn't need to type / look everything up again?

**Comment by doricon** [comment]
Also - can quotes in the name be allowed? (or was quotes the thing that gave a mountain of trouble before?). If not, we need to make sure to put in the field instructions not to use quotes, they commonly get used in taxonomic names because of tenuous systematics. e.g., "Ficus" virginiensis Fontaine)

**Comment by NoisyFlowers** [comment]
https://github.com/paleobot/pbot-dev/issues/273
