### ISSUE TITLE
Unable to edit collection

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#275]
I am trying to edit some collections and when I submit, I get: Error: Unable to cascade groups for Collection

I get this for "Hubble Bubble (USNM 42384. SLW 0503, 0601, 0811)" on stage/prod, and this is a private node. "Hubble Bubble" on dev is a public node, which also gave me the same error. This node was created prior to Hack-a-Thon, I believe. 

I was able to edit node "Deep Sand (USNM 42521. SLW 1009)", which I'd created last week.

**Comment by ecurrano** [comment]
I tried editing another node in stage/prod that I created before Hack-a-Thon and also got the Unable to cascade groups for Collection error.

**Comment by NoisyFlowers** [comment]
When fetching remote nodes for Group cascade in Resolvers.getRelationships, we are not including all fields in the returned results. Later, when Resolvers.isDuplicate runs on a remote node, it cannot find a value for the name field.

This is fixed in paleobot/pbot-api@f187a592ad097eb4840814fd288c2269a0a5f6dc

merged to master, deployed to dev and stage/prod.
