### ISSUE TITLE
PBot Explore: Specimen Search Results

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#289]
Here is a screenshot of what the "Quick Results" would look like for a specimen search. We envisioned this in table format, but this may not be phone/tablet compatible. So, I could also see the information we want to show for each specimen just listed underneath the specimen name.

![Screen Shot 2024-03-07 at 10 05 51 AM](https://github.com/paleobot/pbot-dev/assets/72828382/4fca5fdc-3c68-4549-907a-64b0c40b11e1)

For min and max ages: for standardization on this quick view results, converting everything to international epoch would be preferred. However, if that is too difficult, we could display whatever timescale was entered for min and max by the user.

When people click on a specimen, they would see the full search results, which we hope might look like slide 3 here: https://docs.google.com/presentation/d/15JN5MsiJ5iVnsCLvJEuZ3Y33TVmQvmj4/edit#slide=id.p3.

The Show me more data button is a placeholder to allow for data downloads.

**Comment by NoisyFlowers** [comment]
Some of the summary results is implemented in 
paleobot/pbot-client@11aeab475d9bb0daeb1236e32c813a3c7683cab0

merged to master and running on dev

**Comment by NoisyFlowers** [comment]
There's nothing in our db schema definition to prevent a Specimen from being identifiedAs more than one OTU. But the form definition in the Google doc wants only one "Example of taxon/OTU". 

I'm not sure what to do with that.

**Comment by doricon** [comment]
Oh that's an interesting issue. I think it is fine if the definition does not prevent a specimen from being identifiedAs more than  one OTU (there are cases I can think of, mainly differences in opinion, or taxonomic changes through time) where that may occur.  

It would be nice if the specimen page could show all OTUs that the specimen is assigned to. For the search results table, it would be nice if all OTUs could be listed in results box, but understandable if that doesn't work.... in which case we need to think of a rule or something to determine what is displayed on the results list output. Any ideas here?

**Comment by aazaff** [comment]
I think it is integral to our design that yes a specimen can be identified as more than one OTU. I can think of several reasons for this.

What that then means for the search results is tricky. Why can't we just list them all? You could have it expandable/contractable as an accordion so that it doesn't take up space?

**Comment by NoisyFlowers** [comment]
We do list them all in the current output. But this is not allowed for in the Google doc spec.

**Comment by NoisyFlowers** [comment]
Regarding the accordion idea, as well as the current spec, which shows Descriptions in a box that I assume will be scrollable, and for that matter, my current output, which displays one pic at a time in a slideshow: this sort of presentation is not friendly to printing. Should we be considering that?

**Comment by doricon** [comment]
> We do list them all in the current output. But this is not allowed for in the Google doc spec.
> 
> I'm asking what to do about that.

I would suggest to list sequentially any OTUs (with the associated info) that the specimen has been assigned to. I don't think an accordion is needed there. (this is also likely a rare case situation).

**Comment by doricon** [comment]
> Regarding the accordion idea, as well as the new spec, which shows Descriptions in a box that I assume will be scrollable, and for that matter, my current output, which displays one pic at a time in a slideshow: this sort of presentation is not friendly to printing. Should we be considering that?

This is a good point about the developing on-screen display for specimens (and by extension, likely OTUs as well) not being printer friendly. It would be awesome if they were! I know this is a feature many of us really want/need. Although I am not sure there is an easy or universal solution for this, given that we are, in some cases, holding more info than what is typically displayed on a page. 

Here are a few thoughts for making it easier for specimen and OTU pages to be designed for direct printing: 

(1) image carousel: since we've set up a prioritization for images, there is kind of a "main photo" that should be the first one in the carousel.  I vote that just that one image is what prints (or maybe we say the holotype/exemplar plus "key feature" images). Down the road, maybe we can set up an image search that allows for all the images of a specimen or taxon to be viewed and/or printed. 

(2) The description doesn't have to be in a scrollable box, we could just let that bad boy be as long it needs to be! The box in the design doc is just because we were envisioning it like a one-page screen, but that has kind of evolved... definitely not stuck to that. Since we can have multiple descriptions attached to a specimen and OTU, I think either (a) a sequential list of each description in full, or (b) an accordion for each description may be needed here anyway. Option (a) is of course more amenable to printing directly, it just could take more than one page. Option (b) would be clean and user friendly on-screen (maybe a "print" option would just automatically expand the accordions?)

Thoughts on that? I'm not sure if my response is super helpful...

**Comment by aazaff** [comment]
Sounds like we have a lot to discuss Wednesday. Is this something you can put aside and do something else or do you need an answer now?

From: doricon ***@***.***>
Date: Monday, July 8, 2024 at 3:56 PM
To: paleobot/pbot-dev ***@***.***>
Cc: Zaffos, Andrew - (azaffos) ***@***.***>, Assign ***@***.***>
Subject: [EXT] Re: [paleobot/pbot-dev] PBot Explore: Specimen Search Results (Issue #289)

External Email

________________________________
Regarding the accordion idea, as well as the new spec, which shows Descriptions in a box that I assume will be scrollable, and for that matter, my current output, which displays one pic at a time in a slideshow: this sort of presentation is not friendly to printing. Should we be considering that?

This is a good point about the developing on-screen display for specimens (and by extension, likely OTUs as well) not being printer friendly. It would be awesome if they were! I know this is a feature many of us really want/need. Although I am not sure there is an easy or universal solution for this, given that we are, in some cases, holding more info than what is typically displayed on a page.

Here are a few thoughts for making it easier for specimen and OTU pages to be designed for direct printing:

(1) image carousel: since we've set up a prioritization for images, there is kind of a "main photo" that should be the first one in the carousel. I vote that just that one image is what prints (or maybe we say the holotype/exemplar plus "key feature" images). Down the road, maybe we can set up an image search that allows for all the images of a specimen or taxon to be viewed and/or printed.

(2) The description doesn't have to be in a scrollable box, we could just let that bad boy be as long it needs to be! The box in the design doc is just because we were envisioning it like a one-page screen, but that has kind of evolved... definitely not stuck to that. Since we can have multiple descriptions attached to a specimen and OTU, I think either (a) a sequential list of each description in full, or (b) an accordion for each description may be needed here anyway. Option (a) is of course more amenable to printing directly, it just could take more than one page. Option (b) would be clean and user friendly on-screen (maybe a "print" option would just automatically expand the accordions?)

Thoughts on that? I'm not sure if my response is super helpful...

**Comment by NoisyFlowers** [comment]
I'll put it aside and find some other issues to work on.

I'm starting to wonder if working from that Google doc is the best idea. What we are beginning to describe (full display of descriptions, display of all OTUs) is more like the current output than what is described in that doc. The current output is also fairly print friendly. 

Maybe it would be better to start from what we have and figure out how we'd like to change that? This whole thing could be as simple as changing the headings and how the data is grouped.

**Comment by ecurrano** [comment]
We need to return to this issue- I missed this when I was in the field. It would be great to include what a specimen has been identified as, and I have no problem with listing all of these in the search results table, if that is possible.

**Comment by doricon** [comment]
Revisiting specimen search results, my suggestions after using it: 

(1) specimen search result list: can we add the column for the "identified as: name:" field. If there is more than one (which is anticipated to be not super common), then list all identified as relationships separated by a comma. This info on the results list is really useful, otherwise a list of specimen numbers is rough to sort through!

(2) on the specimen page: can you make the OTU name that the specimen is identified as a hyperlink to that OTU page?

**Comment by aazaff** [comment]
Those are both good. Please put the OTU hyperlink idea as a separate issue

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: doricon ***@***.***>
Sent: Wednesday, September 25, 2024 8:42:56 AM
To: paleobot/pbot-dev ***@***.***>
Cc: Zaffos, Andrew - (azaffos) ***@***.***>; Assign ***@***.***>
Subject: [EXT] Re: [paleobot/pbot-dev] PBot Explore: Specimen Search Results (Issue #289)


External Email

________________________________
Revisiting specimen search results, my suggestions after using it:

(1) specimen search result list: can we add the column for the "identified as: name:" field. If there is more than one (which is anticipated to be not super common), then list all identified as relationships separated by a comma. This info on the results list is really useful, otherwise a list of specimen numbers is rough to sort through!

(2) on the specimen page: can you make the OTU name that the specimen is identified as a hyperlink to that OTU page?

**Comment by doricon** [comment]
closing - leftover items were moved to separate issues. In future we will need to address printing results.
