### ISSUE TITLE
OTU Node- notable features preserved

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#299]
I was trying to edit an OTU node in prod (Artocarpus 2 Bighorn Basin). When I hit submit, nothing happened. I eventually discovered the error hidden in the optional fields accordion (this took me 2 minutes to figure out), under Notable Features. This was a surprise, as I had not edited this field. I was just trying to change the name of the OTU. See the screenshot for error. I can't fix this, as the OTU has none of our notable features and there is not an option in the dropdown for nothing.
<img width="465" alt="Screen Shot 2024-06-04 at 9 10 36 PM" src="https://github.com/paleobot/pbot-dev/assets/72828382/ed075893-2583-42c9-8c0d-582f91382765">

**Comment by ecurrano** [comment]
I tried highlighting a notable feature and then getting rid of it, but still get this error when I try to submit.

**Comment by ecurrano** [comment]
I tried editing an OTU node I created today (BHB "Artocarpus" lessigiana), and it worked fine. I also just tried editing the faulty node to add a notable feature and it wouldn't let me.

**Comment by NoisyFlowers** [comment]
This was a problem with how notableFeatures is populated in the client. 

Fixed in paleobot/pbot-client@31b1a2d8125e24ec4bde734fc0780564f80cf8a9

merge to master and running on dev


Investigating this also uncovered some problems with how OTU fields are populated for mutation from the search dialog. Specifically, they aren't. I've opened a separate issue for this: paleobot/pbot-client#35
