### ISSUE TITLE
Versioning options for different nodes

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#33]
This is a continuation of the versioning issue raised in https://github.com/paleobot/pbot-api/issues/2

What if we take a git-like approach to tracking changes?

![Screenshot 2021-12-02 at 12 31 10 PM](https://user-images.githubusercontent.com/10422595/144490175-48d34c03-c65c-458e-b4ae-09d7092d376e.png)

In short, we track if a change is a CREATE, EDIT, or DELTE as a property of the [ENTERED_BY] relationship. We also track the relevant change made in the [ENTERED_BY].

**Comment by aazaff** [comment]
I think we should not support "true" forking in the database. If a user wants to fork a schema, they have to create an ENTIRELY NEW SCHEMA (form a database perspective). The process of copying over characters and traits should be handled entirely from the CLIENT side.

Users can then MANUALLY create a relation between the original and the "fork" [VARIANT_OF], again through some toggle in the client.

**Comment by NoisyFlowers** [comment]
I like the idea of adding a type field to ENTERER_BY. I'm not sure I like the idea of echoing the changes there. For one thing, how to capture relationship changes? For another, if we're are going to have duplicate data in the db, there might be better ways to do it. 

Here's an article on one approach: [https://medium.com/neo4j/keeping-track-of-graph-changes-using-temporal-versioning-3b0f854536fa](url)

Here's an implementation that is similar: [https://h-omer.github.io/neo4j-versioner-core/](url)

I'm not sold on these either, but that may just be because I haven't accepted the fact that anything we do for versioning is really going to mess up everything we've done so far.

**Comment by NoisyFlowers** [comment]
I'm not sure I understand what you mean by pushing true forking into the client.  

If we do decide to support this within the db, there are apoc routines that could help: [https://neo4j.com/labs/apoc/4.2/graph-updates/graph-refactoring/clone-subgraph/](url)

**Comment by NoisyFlowers** [comment]
Note: The images for the example in that last link seem flawed. I can't see why node7 was discarded on the B tree.

**Comment by aazaff** [comment]
@NoisyFlowers. This is effectively done for now, correct? Can we attach a commit and close this?
