### ISSUE TITLE
Equivalent of Paleobiology Database Publication number?

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#37]
Currently users manually email PBDB to get a publication number to put in your paper acknowledgements to show that it is a PBDB publication - see https://paleobiodb.org/#/publications. Less than 1/3 of publications using PBDB data are on this list. Is there value in doing something like this, or is a google scholar tally like the one Matt Clapham uses sufficient (can't find the link atm)?

Related to #35

**Comment by ecurrano** [comment]
The Smithsonian Evolution of Terrestrial Ecosystems group similarly assigns publication numbers, which were a little bit of a pain, but I get why they do it since that is a working group rather than a research tool / database.

I'm not sure I see the advantage of doing this, given the infrastructure that is involved. Except maybe that you then have papers to put on the website (not sure if this is important) When PBot is operational, I assume we will publish a paper introducing it, which everyone can then cite? And we include explicit information on the website asking people to cite it?

**Comment by clairecleveland** [comment]
I agree that if a simple option is available, it's usually the best.
