### ISSUE TITLE
Request from schema group--needs answer to be able to proceed

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#74]
Hello All,

This question came in from our Pollen and Spores group. They requested a response as soon as possible as they can't move forward with their illustrator until they know the answer. This is regarding adding illustration support to characters in schemas. Thank you, Claire

Matt Pound and I met today to discuss strategies for cost-cutting. We need to maintain the illustrations of individual features, but could, perhaps dispense with images for details of those features by linking to existing imagery, rather than having new generated, as has also been suggested by Surangi. Specifically, would it be possible to have links pointing users to specific pages within Halbritter et al.’s 2018 Open Access Book (https://link.springer.com/content/pdf/10.1007/978-3-319-71365-6.pdf)? While open access, copyright is still held by Springer, rather than a creative commons license, so simply copying images from this source is not possible (same problem with the Punt et al. 2006 Glossary of pollen and spore terminology, where the copyright is held by Elsevier). Halbritter et al.’s work contains both illustrations and photographs of features and is a more extensive treatment than Punt’s.

**Comment by doricon** [comment]
Hi Claire,

Let me see if I understand this correctly - so, there would still be an illustration (or photo) to show what a feature/character is, and then for the details of states there would be a reference and link to the open access Halbritter et al 2018. And the reference with link would be something like: "see Halbritter et al. 2018, pg. 55, fig. A (https://link.springer.com/content/pdf/10.1007/978-3-319-71365-6.pdf)."

If so, I think this is a very reasonable solution and I have no problem with it. The Halbritter book is just WOW. We clearly can't recreate the vast resource of imagery in that 500+ page work.

A couple notes: It looks like we could only link to the whole document, not individual pieces or figs. Which is totally fine, just means that it would be most helpful/easy if each state had a specific page and figure reference. The actual hyperlink could just appear in the character definition, and the states just list the page+fig info. (At least I think that would work with how we will be displaying this info?)

Let me know if I am totally misunderstanding! Happy to chat about it more tomorrow when we meet too, if that is easier.

Cheers!
Dori



Dori L. Contreras, Ph.D.

Curator of Paleobotany
Perot Museum of Nature and Science

E  ***@***.******@***.***>

P  214.756.5783



[pastedGraphic_1.png]<http://www.perotmuseum.org/>



2201 N. Field Street, Dallas, TX 75201  |  perotmuseum.org

[pastedGraphic_2.png]<https://www.facebook.com/PerotMuseum/>

[pastedGraphic_3.png]<https://twitter.com/PerotMuseum>

[pastedGraphic_4.png]<https://www.instagram.com/perotmuseum/>




________________________________
From: clairecleveland ***@***.***>
Sent: Monday, October 31, 2022 11:35 AM
To: paleobot/pbot-dev ***@***.***>
Cc: Dori Contreras ***@***.***>; Assign ***@***.***>
Subject: [paleobot/pbot-dev] Request from schema group--needs answer to be able to proceed (Issue #74)


Hello All,

This question came in from our Pollen and Spores group. They requested a response as soon as possible as they can't move forward with their illustrator until they know the answer. Thank you, Claire

Matt Pound and I met today to discuss strategies for cost-cutting. We need to maintain the illustrations of individual features, but could, perhaps dispense with images for details of those features by linking to existing imagery, rather than having new generated, as has also been suggested by Surangi. Specifically, would it be possible to have links pointing users to specific pages within Halbritter et al.’s 2018 Open Access Book (https://link.springer.com/content/pdf/10.1007/978-3-319-71365-6.pdf)? While open access, copyright is still held by Springer, rather than a creative commons license, so simply copying images from this source is not possible (same problem with the Punt et al. 2006 Glossary of pollen and spore terminology, where the copyright is held by Elsevier). Halbritter et al.’s work contains both illustrations and photographs of features and is a more extensive treatment than Punt’s.

**Comment by aazaff** [comment]
Hi, what Dori describes seems to be a reasonable workaround. The key being that the this external link is saved somewhere other than as an image node - e.g., as Dori suggests saving it in the reference node seems practicable.

I will also note that, last I heard, there have been some recent legal changes or SCOTUS rulings that have made using copyright images even harder to use than before (though I know zero details about this). So it seems better safe than sorry on copyright issues should be our strategy.

**Comment by clairecleveland** [comment]
Ellen--Let me check on publications, last notes were that they WOULD publish with us
Andrew--Duly noted on copyrights 
Dori--The links would be instead of illustrations appearing in PBot

Ellen and Dori we can discuss in meetings tomorrow--we can overlap between 2:00pm and 2:15pm (ET). 
Thank you all,
Claire

**Comment by aazaff** [comment]
Claire says all done.
