### ISSUE TITLE
Add a "blank" option to every select list

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#81]
Right now, if you make a mistake there is no way to clear what you have entered. Here are some examples of things that happen. Not sure if cancel, reset, undo, or empty field option is best for each/all of these.

- ~~V 1.1 You enter several layers of data to edit a character and then realize you need to enter things differently. It would be good to have an option that allows you to reset the screen to blank instead of having to click some other function type like state and then click back to character to get a blank screen again. Possible fix: provide cancel/reset without changing the function type (character, state, person, OTU, etc.) or action type (add, edit, delete).~~
- V 1 You enter the wrong selection from a drop down box and want to leave it blank. Now you can't get rid of your selection. Possible fix: provide a blank entry at the top of each drop down box.
- ~~V 2 (unless this is an easier fix than I think it is and could be V1.1) It would be great to be able to undo our last field entry, but this may be a complicated wish list item.~~

**Comment by aazaff** [comment]
We will have to go into this in more detail at a later date. Not assigning it a priority until we've discussed more thoroughly.

**Comment by NoisyFlowers** [comment]
Note: It also makes no sense to add a None option to multiselects, since they allow you to deselect.

**Comment by NoisyFlowers** [comment]
Ugh. This is a can of worms. 

For complex query forms like OTU, which builds up Schema/Character/State combinations, it's not enough to provide a None option. Choosing None on Schema, for instance, requires that Character and State be reset as well. Since these are shared modular components, this level of state management is complicated. 

I'm thinking of bailing completely on the "None" option and just leaning on the form level Reset button idea, at least until after Hack-a-whatsit.

**Comment by clairecleveland** [comment]
@NoisyFlowers Yeah, I'm good with that Doug. More recently there was a specific case where a required form was causing an issue, but I can't remember the details. I'll report if I come across it again or perhaps it will come out at HackAThon. I got rid of HackAThon label and changed to high priority question for after HackAThon. Please relabel if that's not appropriate. Thanks!

**Comment by NoisyFlowers** [comment]
- I added a Reset button to all forms
- Non-multi selects in Optional accordions now have a None option
- I removed a None option from a Collection option that was in a required accordion

I decided to go ahead with the mutation-related Nones because those forms would be particularly nasty to have to fully reset because of a mistake. I decided not to add Nones to selects in queries because the Schema/Character/State logic mentioned above would require more effort than it is worth for such short forms.

This is in

> paleobot/pbot-client@4dd3926deb2247a8341954aa92dffbfb4d1597d6
> paleobot/pbot-client@0e737243d5ce2865e77aa3dc6c01f6f4b0ed2b30
> paleobot/pbot-client@a1586de708d552fdec3d57f2fc47689c44d95c44
> paleobot/pbot-client@7a087ed80e47d851ed632ee7377326cc4dd6f2ba
> paleobot/pbot-client@4bd809665308d2e6a3f3dcba3f6cb1ead0af1496
> paleobot/pbot-client@f461ecd98dc977b048aef225fde5c41f9ec90c66
> 

Because there were so many files involved, I tagged the code history before bringing these changes so we can roll back if anyone is unhappy.

If this is satisfactory to everyone, I suggest we close this issue.
