### ISSUE TITLE
Cycle through every form where order is possible and implement ordering

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#93]
Everywhere where we track order, then that information should be ordered correctly in returns. This is separate from #80 which is a specific bug.

**Comment by aazaff** [comment]
I believe this is also now implemented can we close? @NoisyFlowers

**Comment by NoisyFlowers** [comment]
I've added ordering via graphql everywhere I could find for Reference and Person (author) nodes. This is in commit
paleobot/pbot-client@4b4da71e872c760c54258a70a539b4ad4984cfdc

CharacterInstance, Character, and State ordering will require sorting on the client side rather than through the graphql query. I'm leaving this open until I can get to that.

**Comment by NoisyFlowers** [comment]
In reviewing the code for displaying CharacterInstances, Characters, and States in both the query results and in mutation forms, I think we are handing order properly. 

I'm closing this issue.
